import { Gender, MaritalStatus, WorkStatus, Status } from '@prisma/client'

export const maritalStatus = [
  { [MaritalStatus.SINGLE]: 'single' },
  { [MaritalStatus.MARRIED]: 'married' },
  { [MaritalStatus.DIVORCED]: 'divorced' },
  { [MaritalStatus.WIDOWED]: 'widowed' },
  { [MaritalStatus.COHABITING]: 'cohabiting' },
]

export const maritalOptions: {
  [key in MaritalStatus]: string
} = Object.assign({}, ...maritalStatus)

export const workStatusOptions = {
  [WorkStatus.EMPLOYEE]: 'employee',
  [WorkStatus.ENTREPRENEUR]: 'entrepreneur',
  [WorkStatus.UNEMPLOYED]: 'unemployed',
  [WorkStatus.STUDENT]: 'student',
  [WorkStatus.RETIRED]: 'retired',
  [WorkStatus.OTHER]: 'other',
}

export const genderOptions = {
  [Gender.MALE]: 'male',
  [Gender.FEMALE]: 'female',
}

export const genderTypes = {
  [Gender.MALE]: 'male_type',
  [Gender.FEMALE]: 'female_type',
}

export const profileStatus = {
  [Status.PENDING]: 'pending',
  [Status.APPROVED]: 'approved',
  [Status.REJECTED]: 'rejected',
  [Status.INCOMPLETE]: 'incomplete',
}

type TranslationFunction = (key: string) => string

export function getTranslatedOptions<T extends Record<string, string>>(
  options: T,
  translate: TranslationFunction,
  prefix: string,
): { [K in keyof T]: string } {
  return Object.fromEntries(
    Object.entries(options).map(
      ([key, value]) => [key, translate(`${prefix}.${value}`)],
    ),
  ) as { [K in keyof T]: string }
}

export const countryKeys = [
  'afghanistan',
  'south_africa',
  'albania',
  'algeria',
  'germany',
  'andorra',
  'angola',
  'antigua_and_barbuda',
  'saudi_arabia',
  'argentina',
  'armenia',
  'australia',
  'austria',
  'azerbaijan',
  'bahamas',
  'bahrain',
  'bangladesh',
  'barbados',
  'belgium',
  'belize',
  'benin',
  'bhutan',
  'belarus',
  'myanmar',
  'bolivia',
  'bosnia_and_herzegovina',
  'botswana',
  'brazil',
  'brunei',
  'bulgaria',
  'burkina_faso',
  'burundi',
  'cambodia',
  'cameroon',
  'canada',
  'cape_verde',
  'central_african_republic',
  'chile',
  'china',
  'cyprus',
  'colombia',
  'comoros',
  'republic_of_congo',
  'democratic_republic_of_congo',
  'north_korea',
  'south_korea',
  'costa_rica',
  'ivory_coast',
  'croatia',
  'cuba',
  'denmark',
  'djibouti',
  'dominica',
  'egypt',
  'united_arab_emirates',
  'ecuador',
  'eritrea',
  'spain',
  'estonia',
  'united_states',
  'ethiopia',
  'fiji',
  'finland',
  'france',
  'gabon',
  'gambia',
  'georgia',
  'ghana',
  'greece',
  'grenada',
  'guatemala',
  'guinea',
  'guinea_bissau',
  'equatorial_guinea',
  'guyana',
  'haiti',
  'honduras',
  'hong_kong',
  'hungary',
  'marshall_islands',
  'solomon_islands',
  'india',
  'indonesia',
  'iran',
  'iraq',
  'ireland',
  'iceland',
  'israel',
  'italy',
  'jamaica',
  'japan',
  'jordan',
  'kazakhstan',
  'kenya',
  'kyrgyzstan',
  'kiribati',
  'kuwait',
  'laos',
  'lesotho',
  'latvia',
  'lebanon',
  'liberia',
  'libya',
  'liechtenstein',
  'lithuania',
  'luxembourg',
  'macedonia',
  'madagascar',
  'malaysia',
  'malawi',
  'maldives',
  'mali',
  'malta',
  'morocco',
  'cook_islands',
  'mauritius',
  'mauritania',
  'mexico',
  'micronesia',
  'moldova',
  'monaco',
  'mongolia',
  'montenegro',
  'mozambique',
  'namibia',
  'nauru',
  'nepal',
  'nicaragua',
  'niger',
  'nigeria',
  'niue',
  'norway',
  'new_zealand',
  'oman',
  'uganda',
  'uzbekistan',
  'pakistan',
  'palau',
  'panama',
  'papua_new_guinea',
  'paraguay',
  'netherlands',
  'peru',
  'philippines',
  'poland',
  'portugal',
  'qatar',
  'dominican_republic',
  'czech_republic',
  'romania',
  'united_kingdom',
  'russia',
  'rwanda',
  'saint_kitts_and_nevis',
  'saint_lucia',
  'san_marino',
  'saint_vincent_and_grenadines',
  'el_salvador',
  'samoa',
  'sao_tome_and_principe',
  'senegal',
  'serbia',
  'seychelles',
  'sierra_leone',
  'singapore',
  'slovakia',
  'slovenia',
  'somalia',
  'sudan',
  'south_sudan',
  'sri_lanka',
  'sweden',
  'switzerland',
  'suriname',
  'swaziland',
  'syria',
  'tajikistan',
  'tanzania',
  'chad',
  'thailand',
  'east_timor',
  'togo',
  'tonga',
  'trinidad_and_tobago',
  'tunisia',
  'turkmenistan',
  'turkey',
  'tuvalu',
  'ukraine',
  'uruguay',
  'vanuatu',
  'vatican',
  'venezuela',
  'vietnam',
  'yemen',
  'zambia',
  'zimbabwe',
] as const

export type CountryKey = typeof countryKeys[number];